import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'EULA - Fishinity Pro',
  description: 'End-User License Agreement untuk aplikasi Fishinity Pro.',
}

export default function EulaPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white shadow-sm rounded-lg p-8 border border-gray-200">
        
        {/* Header */}
        <header className="mb-8 border-b pb-4">
          <h1 className="text-3xl font-bold text-gray-900">End-User License Agreement</h1>
          {/* Updated at December 16th, 2025 [cite: 2] */}
          <p className="text-gray-500 mt-2 text-sm">Updated at December 16th, 2025</p>
        </header>

        {/* Content */}
        <article className="prose prose-slate max-w-none text-gray-700 space-y-8">
          
          <section>
            {/* [cite: 4] */}
            <p className="font-medium text-lg">
              Fishinity Pro hereby grants you access to ("the app") and invites you to purchase the services offered here.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Definitions and Key Terms</h2>
            <p>To help explain things as clearly as possible in this Eula, every time any of these terms are referenced, are strictly defined as:</p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>
                <strong>Cookie:</strong> small amount of data generated by a website/app and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
              </li>
              <li>
                {/* [cite: 13] */}
                <strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to <strong>Fishinity Pro Ltd</strong> (Top Floor, Claridon House, London Road, Stanford - Le Hope, Essex, SS17 0JU), that is responsible for your information under this Eula.
              </li>
              <li>
                {/* [cite: 16] */}
                <strong>Country:</strong> where Fishinity Pro or the owners/founders of Fishinity Pro are based, in this case is <strong>England</strong>.
              </li>
              <li>
                 {/* [cite: 21] */}
                 <strong>App/Application:</strong> Fishinity Pro app, refers to the SOFTWARE PRODUCT identified above.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Introduction</h2>
            {/* [cite: 25, 26] */}
            <p>
              This End User License Agreement (the "Agreement") is a binding agreement between you ("End User", "you" or "your") and Fishinity Pro Ltd ("Company", "we", "us" or "our"). This Agreement governs the relationship between you and us, and your use of the Company Fishinity Pro.
            </p>
            {/* [cite: 40] */}
            <p className="mt-4">
               By downloading, installing, accessing, or using the app you: (a) affirm that you have all of the necessary permissions and authorisations to access and use the app; (b) if you are using the app pursuant to a license purchased by an organisation, that you are authorised by that organisation to access and use the app; (c) acknowledge that you have read and that you understand this agreement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">License</h2>
            {/* [cite: 54, 55] */}
            <p>
              Subject to the terms of this Agreement and, if applicable, those terms provided in the License Agreement, Fishinity Pro grants you a limited, non-exclusive, perpetual, revocable, and non-transferable license to:
            </p>
            <ul className="list-none mt-2 space-y-2 pl-2">
              <li>(a) download, install and use the Software on one (1) Computing Device per single user license that you have purchased and been granted.</li>
              <li>(b) access, view, and use on such Computing Device the End User Provided Materials made available in or otherwise accessible through the Software.</li>
              <li>(c) install and use the trial version of the Software on any number of Computing Devices for a trial period of fifteen (15) unique days after installation.</li>
              <li>(d) receive updates and new features that become available during the one (1) year period from the date on which you purchased the license to the Software.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Restrictions</h2>
            <p>You agree not to, and you will not permit others to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              {/* [cite: 68] */}
              <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the Application or make the Application available to any third party.</li>
              {/* [cite: 71] */}
              <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the Application.</li>
              {/* [cite: 74] */}
              <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Fishinity Pro or its affiliates, partners, suppliers or the licensors of the Application.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Intellectual Property</h2>
            {/* [cite: 78] */}
            <p>
              All intellectual property rights, including copyrights, patents, patent disclosures and inventions (whether patentable or not), trademarks service marks, trade secrets, know-how and other confidential information, trade dress, trade names, logos, corporate names and domain names, together with all of the good will associated there with, derivative works and all other rights (collectively, "Intellectual Property Rights") that are part of the Software that are otherwise owned by Fishinity Pro shall always remain the exclusive property of Fishinity Pro.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Term and Termination</h2>
            {/* [cite: 135, 140] */}
            <p>
              This Agreement shall remain in effect until terminated by you or Fishinity Pro. Fishinity Pro may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
            </p>
            <p className="mt-2">
              Upon termination of this Agreement, you shall cease all use of the Application and delete all copies of the Application from your computer.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">No Warranties</h2>
             {/* [cite: 159] */}
            <p>
               The Application is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Fishinity Pro expressly disclaims all warranties, whether express, implied, statutory or otherwise.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Limitation of Liability</h2>
             {/* [cite: 177] */}
            <p>
              Notwithstanding any damages that you might incur, the entire liability of Fishinity Pro and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the Application.
            </p>
          </section>

          <section className="border-t pt-6 mt-8">
            <h2 className="text-xl font-bold text-gray-900 mb-2">Contact Us</h2>
            {/* [cite: 254] */}
            <p>Don&apos;t hesitate to contact us if you have any questions about this Agreement.</p>
            <ul className="list-none mt-2">
              <li>
                <span className="font-semibold">Via Email:</span> <a href="mailto:info@fishinitypro.app" className="text-blue-600 hover:underline">info@fishinitypro.app</a>
              </li>
            </ul>
          </section>

        </article>
      </div>
    </div>
  )
}