import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy - Fishinity Pro',
  description: 'Kebijakan Privasi untuk aplikasi Fishinity Pro.',
}

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white shadow-sm rounded-lg p-8 border border-gray-200">
        
        {/* Header */}
        <header className="mb-8 border-b pb-4">
          <h1 className="text-3xl font-bold text-gray-900">Privacy Policy</h1>
          {/* Updated at December 16th, 2025 */}
          <p className="text-gray-500 mt-2 text-sm">Updated at December 16th, 2025</p>
        </header>

        {/* Content */}
        <article className="prose prose-slate max-w-none text-gray-700 space-y-8">
          
          <section>
            {/* */}
            <p>
              Fishinity Pro ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Fishinity Pro.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Definitions and Key Terms</h2>
            <p>To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
               {/* */}
              <li>
                <strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
              </li>
              <li>
                {/* */}
                <strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it refers to <strong>Fishinity Pro Ltd</strong> (Top Floor, Claridon House, London Road, Stanford-Le-hope, Essex, SS17 0JU), that is responsible for your information under this Privacy Policy.
              </li>
              <li>
                <strong>Country:</strong> where Fishinity Pro or the owners/founders of Fishinity Pro are based, in this case is <strong>England</strong>.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">What Information Do We Collect?</h2>
            {/* */}
            <p>We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Name / Username</li>
              <li>Phone Numbers</li>
              <li>Email Addresses</li>
              <li>Mailing Addresses</li>
              <li>Billing Addresses</li>
              <li>Debit/credit card numbers</li>
              <li>Age</li>
              <li>Password</li>
            </ul>
             {/* */}
            <p className="mt-4">We also collect information from mobile devices for a better user experience, although these features are completely optional:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Location (GPS)</li>
                <li>Phonebook (Contacts list)</li>
                <li>Camera (Pictures)</li>
                <li>Photo Gallery (Pictures)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">How Do We Use The Information We Collect?</h2>
             {/* */}
            <p>Any of the information we collect from you may be used in one of the following ways:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>To personalize your experience</li>
              <li>To improve our website</li>
              <li>To improve customer service</li>
              <li>To process transactions</li>
              <li>To administer a contest, promotion, survey or other site feature</li>
              <li>To send periodic emails</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">How Long Do We Keep Your Information?</h2>
             {/* */}
            <p>
              We keep your information only so long as we need it to provide Fishinity Pro to you and fulfill the purposes described in this policy. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we&apos;ll either remove it from our systems or depersonalize it so that we can&apos;t identify you.
            </p>
          </section>
          
           <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">General Data Protection Regulation (GDPR)</h2>
             {/* */}
            <p>
              We may be collecting and using information from you if you are from the European Economic Area (EEA). We are committed to helping our customers meet the data subject rights requirements of GDPR.
            </p>
             {/* */}
             <p className="mt-2">
                 We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.
             </p>
          </section>

           <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">California Residents</h2>
             {/* */}
            <p>
              The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it. You may exercise the following rights:
            </p>
             <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Right to Know and Access.</li>
              <li>Right to Equal Service.</li>
              <li>Right to Delete.</li>
              <li>Request that a business not sell your personal data.</li>
            </ul>
          </section>

          <section className="border-t pt-6 mt-8">
            <h2 className="text-xl font-bold text-gray-900 mb-2">Contact Us</h2>
            <p>Don&apos;t hesitate to contact us if you have any questions.</p>
            <ul className="list-none mt-2">
              {/* */}
              <li>
                <span className="font-semibold">Via Email:</span> <a href="mailto:info@fishinitypro.app" className="text-blue-600 hover:underline">info@fishinitypro.app</a>
              </li>
            </ul>
          </section>

        </article>
      </div>
    </div>
  )
}