import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions - Fishinity Pro',
  description: 'Syarat dan Ketentuan penggunaan aplikasi Fishinity Pro.',
}

export default function TermsConditionsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white shadow-sm rounded-lg p-8 border border-gray-200">
        
        {/* Header */}
        <header className="mb-8 border-b pb-4">
          <h1 className="text-3xl font-bold text-gray-900">Terms & Conditions</h1>
          {/* Updated at December 16th, 2025  */}
          <p className="text-gray-500 mt-2 text-sm">Updated at December 16th, 2025</p>
        </header>

        {/* Content */}
        <article className="prose prose-slate max-w-none text-gray-700 space-y-8">
          
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">General Terms</h2>
            {/* [cite: 4, 12] */}
            <p>
              By accessing and placing an order with Fishinity Pro, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Fishinity Pro.
            </p>
            {/* [cite: 6] */}
            <p className="mt-2">
              Under no circumstances shall Fishinity Pro team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Fishinity Pro team or an authorized representative has been advised of the possibility of such damages.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">License</h2>
            {/* [cite: 11] */}
            <p>
              Fishinity Pro grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Definitions and Key Terms</h2>
            <p>To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:</p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>
                <strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information {/* [cite: 19, 20] */}.
              </li>
              <li>
                <strong>Company:</strong> when this terms mention "Company," "we," "us," or "our," it refers to <strong>Fishinity Pro Ltd</strong> (Top Floor, Claridon House, London Raod, Stanford-Le-Hope, Essex, SS17 0JU), that is responsible for your information under this Terms & Conditions {/*  */}.
              </li>
              <li>
                <strong>Country:</strong> where Fishinity Pro or the owners/founders of Fishinity Pro are based, in this case is <strong>England</strong> {/* [cite: 22] */}.
              </li>
              <li>
                <strong>Service:</strong> refers to the service provided by Fishinity Pro as described in the relative terms (if available) and on this platform {/* [cite: 25] */}.
              </li>
              <li>
                 <strong>Website:</strong> Fishinity Pro&apos;s site, which can be accessed via this URL: www.fishinitypro.app {/* [cite: 27] */}.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Return and Refund Policy</h2>
            {/* [cite: 36, 40] */}
            <p>
              Thanks for shopping at Fishinity Pro. If, for any reason, You are not completely satisfied with any good or service that we provide, don&apos;t hesitate to contact us and we will discuss any of the issues you are going through with our product.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Your Consent</h2>
            {/* [cite: 48] */}
            <p>
              By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Cookies</h2>
            {/* [cite: 56, 58] */}
            <p>
              Fishinity Pro uses "Cookies" to identify the areas of our website that you have visited. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Changes To Our Terms & Conditions</h2>
            {/* [cite: 67] */}
            <p>
              If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-2">Limitation of Liability</h2>
            {/* [cite: 109, 110] */}
            <p>
              Notwithstanding any damages that you might incur, the entire liability of Fishinity Pro and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website. To the maximum extent permitted by applicable law, in no event shall Fishinity Pro or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever.
            </p>
          </section>

          <section className="border-t pt-6 mt-8">
            <h2 className="text-xl font-bold text-gray-900 mb-2">Contact Us</h2>
            <p>Don&apos;t hesitate to contact us if you have any questions.</p>
            <ul className="list-none mt-2">
              {/*  */}
              <li>
                <span className="font-semibold">Via Email:</span> <a href="mailto:info@fishinitypro.app" className="text-blue-600 hover:underline">info@fishinitypro.app</a>
              </li>
            </ul>
          </section>

        </article>
      </div>
    </div>
  )
}